name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: sudo apt install protobuf-compiler -y
      run: cargo build --verbose --features=github,llamafile
    - name: Run tests
      run: cargo test --verbose
